version: "3.7"
services:
  web1:
    build: ./quote_gen
    ports:
      - "4999-5000:5000"
    deploy:
      mode: replicated
      replicas: 2
  web2:
    build: ./quote_disp
    expose:
      - "5000"
    ports:
      - "4055-5001:5001"
    depends_on:
      - web1
    deploy:
      mode: replicated
      replicas: 2